#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00

# Make output directories
mkdir -p out_figs


singularity exec docker://brainlife/mne:1.0.2 python3 main.py

cat << EOF > product.json
{
    "brainlife": [
       {
           "type": "image/png",
	         "name": "Cross Validation Scores",
           "base64": "$(base64 -w 0 out_figs/Cross-Validation-Scores.png)"
       }


]
}
EOF
